### ISSUE TITLE
Permalinks altered

### ISSUE THREAD

**Issue by pioneerskies** [wp-cli/server-command#9] opened 2015-01-28 10:39 UTC
Hi there :)

A question: is just a problem of mine to have permalinks altered like this using wp server?

![screenshot 2015-01-28 11 36 08](https://cloud.githubusercontent.com/assets/904690/5936154/22e08832-a6e2-11e4-9af9-0355c113279c.png)

that way I have to use a custom one to get WP work: `/%postname%/`

**Comment by scribu** [comment] 2015-01-28 15:24
The command alters the values of `home` and `siteurl` options at runtime.

> that way I have to use a custom one to get WP work: /%postname%/

Not sure what you mean by "get WP work".

**Comment by pioneerskies** [comment] 2015-01-28 18:25
So it is expected. Glad to hear that :+1: 

Get it work means that is I select "post name" and save the rewrite rule, it will be `index.php/%postname%/` and it will break al the routing (just 404 pages).

If it's all as it could be you can close this issue.

Thank you very much for replying

**Comment by scribu** [comment] 2015-01-28 18:46
If the problem is the `index.php` part, I think it could be fixed by altering the flag that tells WP that rewrites are supported by the server.

**Comment by scribu** [comment] 2015-01-28 18:54
Please try the change in #10 and let me know if it helps.

**Comment by pioneerskies** [comment] 2015-01-29 09:03
Yep yep! It just worked!
:smiley:

**Comment by scribu** [comment] 2015-01-29 11:40
Cool; merged. :)

**Closed** 2015-01-29 11:40 UTC
